# permissions for end users to view cloudstackaffinitygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudstackaffinitygroup-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - cloudstackaffinitygroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - cloudstackaffinitygroups/status
  verbs:
  - get
